# Generated by Django 6.0.3 on 2026-03-17 22:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-date", "title"]},
        ),
        migrations.AlterUniqueTogether(
            name="eventregistration",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("title", "date", "location"), name="unique_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventregistration",
            constraint=models.UniqueConstraint(
                fields=("user", "event"), name="unique_register"
            ),
        ),
    ]
