# Generated by Django 6.0.3 on 2026-03-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="activationtoken",
            name="token",
            field=models.CharField(
                default="xyYccNzDy1Eed9jyUqqVaQn2dfHot5PaLtOtfW0moRhLe3bg",
                max_length=64,
                unique=True,
            ),
        ),
    ]
