# Generated by Django 6.0.3 on 2026-03-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activationtoken",
            name="token",
            field=models.CharField(
                default="xBZDhmd7M6e7O2JzwpS8TdeAxvtQGCKY5Ri7l5hDJxZXUzDq",
                max_length=64,
                unique=True,
            ),
        ),
    ]
