# Generated by Django 6.0.3 on 2026-03-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_activationtoken_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activationtoken",
            name="token",
            field=models.CharField(
                default="bhcsE505Ic7x5UQyFNbXFVId8YRzvmSWroyH5jnKhHSkFhmP",
                max_length=64,
                unique=True,
            ),
        ),
    ]
